import os
import sys
from pathlib import Path

repos_dir = Path("repos")

for repo_path in repos_dir.iterdir():
    if not repo_path.is_dir():
        continue

    repo_name = repo_path.name
    pyproject_path = repo_path / "pyproject.toml"
    setup_py_path = repo_path / "setup.py"

    top_dirs = []
    top_py_files = []

    for item in repo_path.iterdir():
        if item.name.startswith(".") or item.name in ["venv", "__pycache__", "build", "dist", ".pytest_cache"]:
            continue
        if item.is_dir():
            has_py = any(item.glob("**/*.py"))
            if has_py:
                top_dirs.append(item.name)
        elif item.is_file() and item.suffix == ".py" and item.name != "setup.py":
            top_py_files.append(item.stem)

    norm_name = repo_name.replace("-", "_")
    pkg_dir = repo_path / norm_name
    if not pkg_dir.exists() and not (repo_path / f"{norm_name}.py").exists() and norm_name not in top_dirs:
        pkg_dir.mkdir(parents=True, exist_ok=True)
        (pkg_dir / "__init__.py").write_text(f'"""Autogenerated module for {repo_name}"""\n__version__ = "0.1.0"\n', encoding="utf-8")
        top_dirs.append(norm_name)

    # Odpravi flat-layout setuptools napako z eksplicitno definicijo packages in py-modules
    formatted_packages = ", ".join([f'"{d}"' for d in top_dirs])
    formatted_py_modules = ", ".join([f'"{m}"' for m in top_py_files])

    toml_content = f"""[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{repo_name}"
version = "0.1.0"
description = "Rob AI Studio package {repo_name}"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = [{formatted_packages}]
py-modules = [{formatted_py_modules}]
"""
    pyproject_path.write_text(toml_content, encoding="utf-8")
    readme_path = repo_path / "README.md"
    if not readme_path.exists():
        readme_path.write_text(f"# {repo_name}\n", encoding="utf-8")

print("✅ Manifesti in paketne strukture za vseh 6 repozitorijev so uspešno prilagojene!")
